### ISSUE TITLE
No detection of which services have been performed

### ISSUE THREAD

**Issue by MrHrulgin** [Malurth/Auto-2-day-HCCS#4]
Having failed to complete day 1 by rollover, when I ran the script again later that evening, it started buffing and feeding for day 2's plan despite none of day 1's services being completed.

**Comment by Malurth** [comment]
(whoops, didn't mean to close this, thought it was your other issue, that you apparently closed yourself before I got to it :p)

yeah the script is structured to just run day 1's stuff on the first day and run day 2's stuff on the second day. If you didn't manage to actually finish day 1's stuff before rollover your run is almost certainly screwed anyway, frankly, so I don't think making it more flexible in this manner would really be beneficial.

**Comment by MrHrulgin** [comment]
Is it possible to handle each service separately? The script failed before I'd done even the first one on day one, so it wouldn't have been an offence from my perspective to have re-run day 1. If nothing else, is there a way to make it think it's day 1 again so I don't have to do this run manually before I can try the script again?

**Comment by Malurth** [comment]
well how it works it it just checks which day you are in, then runs that day, skipping any tasks that it has saved as being already done

So if you wanna manually run day 1 despite it being day 2, find the line near the bottom of the script:

<pre>if (my_daycount() == 1 && actuallyrun) {</pre>

change '== 1' to '== 2' and it will run the day 1 portion for you. It should pick up where you left off, but it will probably screw with the script overall since there's a lot of stuff that's day-dependent (summons, consumables, etc).

**Comment by MrHrulgin** [comment]
Cool, thank you. If it can handle a chunk of it, it'll still be appreciated. 

Edit: 

> call scripts\AutoHCCS.ash

Running HCCS Day 1...
Day 1 complete!!

**Comment by Malurth** [comment]
yeah so I guess it didn't pick up where it left off. I'm guessing it ran day 2 and saved your progress. You can change that manually too, in data/AutoHCCSvars.txt; the variable "questStage" is where it picks off from; the code

<pre>saveProgress(int questStage);</pre> is used to denote what to skip. So you'd have to comb through the code a bit, prolly searching for that function being called, but you just change that variable in AutoHCCSvars.txt, save the file, and run it again.

**Comment by MrHrulgin** [comment]
Thank you.
